# Site settings
title: Jeffaccino
email: jeffmcnd@gmail.com
description: >
  Jeffrey McNally-Dawes
baseurl: ""
url: "http://jeffaccino.xyz"
twitter_username: jeffmcnd
github_username: jeffmcnd
facebook_username:  jeffmcnd

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
