# Site settings
title: jeffaccino
email: jeffmcnd@gmail.com
description: >
  The travel blog for my adventures through the world.
baseurl: ""
url: "http://jeffaccino.xyz"
twitter_username: jeffmcnd
github_username: jeffmcnd
facebook_username:  jeffmcnd
header-img: img/trees.jpg

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
